name: Test Build

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: pip-packs
        restore-keys: |
          pip-packs
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install wheel
        pip install setuptools twine pygithub
    - name: Find latest release
      env:
        token: ${{ secrets.REL_PAT }}
      run: |
        python3 releasefind.py
    - name: Build
      run: |
        python3 setup.py sdist bdist_wheel
