name: Test lint and build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: pip-packs
        restore-keys: |
          pip-packs
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 wheel setuptools pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test building
      run: |
        python3 setup.py sdist bdist_wheel
        pip install dist/*.whl
    - name: Test emailHelpers with coverage and pytest
      run: |
        coverage run -m pytest test.py
        coverage report -m
        coverage annotate
    - name: Uninstall emailHelpers
      run: pip uninstall emailHelpers -y
    - name: Push reports
      if: ${{ matrix.python-version }} == 3.8
      run: |
        git rm * || true
        git add "emailHelpers/__init__.py,cover" || true
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'KTibow@users.noreply.github.com'
        git commit -am "Coverage" || true
        git switch coverage
        git rm * || true
        git add "emailHelpers/__init__.py,cover" || true
        git commit -am "Coverage" || true
        git push origin HEAD:coverage || true
