# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created, edited]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install setuptools wheel twine pygithub
    - name: Find latest release
      env:
        token: ${{ secrets.REL_PAT }}
      run: |
        python3 releasefind.py
    - name: Push to master
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'KTibow@users.noreply.github.com'
        git commit -am "Automated" || true
        git push origin HEAD:master || true
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python3 setup.py sdist bdist_wheel
        python3 -m twine upload --repository-url https://github.com/family-richards/Python-Email-Helpers dist/*
