name: VirusTotal Check

on:
  schedule:
    - cron: '0 */6 * * *'
  release:
    - types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/cache@v1
      name: Restore cache
      with:
        path: ~/.cache/pip
        key: pip-packs-${{ hashFiles('**/publishrequirements.txt') }}
        restore-keys: |
          pip-packs-
          pip-packs
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r publishrequirements.txt
    - name: Build
      run: |
        python3 setup.py sdist bdist_wheel
    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v2
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        files: |
          **/*
